### ISSUE TITLE
[Feature Request] KIPRIS (특허정보넷) 등록 요청

### ISSUE THREAD

**Issue by supers205** [Alex4386/turnoff-namuwiki#21]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [x] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [ ] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)

KIPRIS(특허정보넷)는 여러 방면에서 뛰어난 특허 논문 사이트입니다. 실제로 단순히 상품이나 공법 개발용으로는 KIPRIS에서 도움을 얻은 사람들이 실제로 많았고, 특히 특허 등록 과정은 물론 특허 거부 사례도 모두 등록 되어 있어 편향된 정보가 없으며, 국내 특허 뿐만 아니라 해외 특허도 거의 등록이 완료되어 자료의 범위 또한 매우 넓습니다.

**Comment by Alex4386** [comment]
### Milestone
0.6.4

**Comment by Alex4386** [comment]
0.6.4 was fix release, 0.7.0에 intelliBan과 동시에 릴리즈 예정.

**Comment by Alex4386** [comment]
현재 설정화면 상 공간 문제로 인해 설정페이지를 추후 따로 분리할 예정입니다.

**Comment by Alex4386** [comment]
![image](https://user-images.githubusercontent.com/27724108/77597463-4850c900-6f42-11ea-9122-d6e19a59a320.png)
  
KIPRIS 측에서 CP949를 인코딩으로 사용하는 관계로 다소 힘들 것 같습니다.

**Comment by Alex4386** [comment]
iconv for browser 가 나올 때 까지 해당 이슈는 [wontfix] 처리 하겠습니다.
