### ISSUE TITLE
[Feature Request] Project intelliBan (DRAFT)

### ISSUE THREAD

**Issue by Alex4386** [Alex4386/turnoff-namuwiki#22]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [X] UX (사용자 경험) 개선 (User Experience Enhancements)
- [ ] 그 외 (Others)  
  
## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)  
서브컬쳐 측은 citation을 그다지 잘 받을 수 없으므로 Firebase RealTime Database 기반의 데이터베이스를 구축하여 해당 내용에 대하여는 나무위키 접속을 허용함. 스위치로 켜고 끌수 있어야 함  

### 기술적 애로사항
- 현재 컨트롤 패널에서 넣을 수 있는 공간이 더이상 없음. 

### Milestone
0.7.0

**Comment by Alex4386** [comment]
089e973caccd90f8d040534a5fb18513b5f55ae5, 4064eed095bba515ff3b83f4c1f89f6bb35d8b2e 커밋으로 처리 완료. 이슈 닫음.
