### ISSUE TITLE
[Feature Request] 개발자 기여에 관련한 규칙 추가

### ISSUE THREAD

**Issue by park012241** [Alex4386/turnoff-namuwiki#36]
# ISSUE: Feature Request
## 추가를 원하는 기능이 무엇인가요? What kind of feature you are requesting?
- [ ] 논문 웹페이지 추가 지원 (more journal page support)  
- [ ] 나무위키 제거 검색엔진 추가 (more search result filters for Search Engine)  
- [ ] UX (사용자 경험) 개선 (User Experience Enhancements)
- [x] 그 외 (Others)  

## 어떤 기능을 추가했으면 좋을까요? (What feature you are requesting?)
**정확하게 설명해 주세요** (Please explain it in detail)

개발자마다 개발 환경과 코드 규칙이 다르므로 확실히 정의할 필요가 있을 것 같습니다.
```Ctrl + Alt + L```과 같은 단축키들로 코드를 정렬할 때에 서로의 설정이 맞지 않아 과다한 수정, 또는 Merge Conflict가 발생할 것 같습니다.

Lint의 필요성도 조금 있어보입니다

**Comment by Alex4386** [comment]
# TODO

* [ ] ESLint
* [ ] ESLint Typescript
* [ ] Webpack?
* [ ] ????

**Comment by zeroday0619** [comment]
린터로 이거 사용하는 건 어떤가요?
[https://github.com/xojs/xo](https://github.com/xojs/xo)
